### ISSUE TITLE
How to fill color outside of the viewport ?

### ISSUE THREAD

**Issue by ektasahu027** [codempireio/react-native-maps-clusterize#11]
Do you have any idea how to fill color outside of the viewport when we draw polygon?
 ```
priorityMarker={
              <Polygon
                ref={map}
                key={markes.id}
                coordinates={markes.coordinates}
                holes={markes.holes}
                strokeColor="red"
                fillColor="rgba(0,128,0,0.3)"
                strokeWidth={4}
              />
            )
 }
```

**Comment by dimagreat** [comment]
@ektasahu027 Sorry, I don't get your problem. Could you give me more information about what do you want to implement?

**Comment by ektasahu027** [comment]
![20190718_104050](https://user-images.githubusercontent.com/41745899/61430795-c935da80-a948-11e9-9204-586807af4144.jpg)
![20190718_104103](https://user-images.githubusercontent.com/41745899/61430796-c935da80-a948-11e9-8244-221d64a9fb6c.jpg)

See in the first image the light back overlay has outside of the box and the marker show inside the box and In the next image I am able to fill overly light green color inside the box but I want to fill it outside of the box like same as in first image.

**Comment by dimagreat** [comment]
@ektasahu027 Almost got you. Could you create js snippet with first and second cases? I'll provide detailed explanation then :)
