### ISSUE TITLE
How do i set custom animation on clicking cluster?

### ISSUE THREAD

**Issue by pratikg711** [codempireio/react-native-maps-clusterize#12]

**Comment by dimagreat** [comment]
Hi @pratikg711 Are you amination when you want to zoom in? Or another one. GIF will help us a lot :)

**Comment by pratikg711** [comment]
@dimagreat Zoom in type

**Comment by dimagreat** [comment]
Sorry @pratikg711, I still don't understand what animation you want to implement. Could you provide more information about your task?
