### ISSUE TITLE
markers not coming when data is coming dynamically 

### ISSUE THREAD

**Issue by visheshtungare-hiteshi** [codempireio/react-native-maps-clusterize#15]
markers not coming when data is coming dynamically  
That is when we are calling the API for the markers then markers are not getting shown

**Comment by dimagreat** [comment]
Hi @visheshtungare-hiteshi, thanks for an issue. Could you share a snippet where we can understand what you want to implement?

**Comment by visheshtungare-hiteshi** [comment]
`<ClusterMap
          // ref={ref => {
          //   if (ref != null) {
          //     ref.fitToElements(true);
          //   }
          // }}
          // ref={ref => {
          //   this.map = ref;
          // }}
          key={`${placeName.latitude}`}
          scrollEnabled={polygonDrawEnable}
          renderClusterMarker={renderCluster}
          region={{
            latitude: parseFloat(placeName.latitude),
            longitude: parseFloat(placeName.longitude),
            latitudeDelta: 0.01,
            longitudeDelta: 0.01
          }}
          onRegionChangeComplete={async center => {
            // console.log("api call", center);

            if (polygonDrawEnable) {
              // var FinalData = await this.map.getMapBoundaries();
              // let DataValue;
              // (DataValue.viewport_sw_lat =
              //   center.latitude - center.latitudeDelta / 2),
              //   (DataValue.viewport_sw_lng =
              //     center.longitude - center.longitudeDelta / 2),
              //   (DataValue.viewport_ne_lat =
              //     center.latitude + center.latitudeDelta / 2),
              //   (DataValue.viewport_ne_lng =
              //     center.longitude + center.longitudeDelta / 2);
              // var DataValue = state.FilterData;
              // (DataValue.viewport_sw_lat = FinalData.southWest.latitude),
              //   (DataValue.viewport_sw_lng = FinalData.southWest.longitude),
              //   (DataValue.viewport_ne_lat = FinalData.northEast.latitude),
              //   (DataValue.viewport_ne_lng = FinalData.northEast.longitude);
               //!use the console method from the global method
              console.log(
                "region coordinates",
                center.latitude - center.latitudeDelta / 2,
                center.longitude - center.longitudeDelta / 2,
                center.latitude + center.latitudeDelta / 2,
                center.longitude + center.longitudeDelta / 2
              );
              // if (datasf == 1) {
              //   datasf = datasf + 1;
              // } else {
              this.apiCall1({
                Coordinates: {
                  NorthEast: [
                    center.longitude + center.longitudeDelta / 2,
                    center.latitude + center.latitudeDelta / 2
                  ],
                  SouthWest: [
                    // center.latitude - center.latitudeDelta / 2,
                    center.longitude - center.longitudeDelta / 2,
                    center.latitude - center.latitudeDelta / 2
                  ]
                }
              });
              // }
            }
          }}
          mapType={MapViewSet}
          onPress={e => {
            if (e.nativeEvent.action !== "marker-press") {
              setMarkerClickData({});
              setMarkerClick(true);
            } else {
              // pressed the map
            }
          }}
          onPanDrag={e => this.onPress(e)}
          priorityMarker={
            editing &&
            (editing.coordinates.length != 0 && (
              <Polygon
                ref={map}
                key={editing.id}
                coordinates={editing.coordinates}
                holes={editing.holes}
                strokeColor="red"
                fillColor="rgba(0,128,0,0.3)"
                strokeWidth={4}
              />
            ))
          }
        >
          {Array.isArray(mapinfo.mapData) && //.slice(0, 30)
            mapinfo.mapData.map(
              marker => (
                 //!use the console method from the global method
                console.log("forceUpdate object", mapinfo.mapData),
                
                (
                  <Marker 
                  color="#00AFF0"
                  coordinate={{
                    latitude:marker.latitude,
                    longitude:marker.longitude
                  }}
                  >
                    <Text style={{ color: "black" }}>{marker.ListPrice}</Text>
                  </Marker>
                  
                //   <Marker
                //     key={marker._id}
                //     coordinate={{
                //       latitude:
                //         Platform.OS == "android"
                //           ? isNaN(parseFloat(marker.latitude))
                //             ? 0
                //             : parseFloat(marker.latitude)
                //           : marker.latitude,
                //       longitude:
                //         Platform.OS == "android"
                //           ? isNaN(parseFloat(marker.longitude))
                //             ? 0
                //             : parseFloat(marker.longitude)
                //           : marker.longitude
                //     }}
                //     onPress={e => {
                //       // alert("click");
                //       setMarkerClickData(marker);
                //       setMarkerClick(false);
                //     }}
                //   >
                //     <Text style={{ color: "black" }}>{marker.ListPrice}</Text>
                //     {/* <AnimatedPriceMarker
                //   onClick={forceUpdate}
                //   amount={`${marker.ListPrice}K`}
                //   color="#00AFF0"
                // /> */}
                //   </Marker>
                )
              )
            )}
          {/* {Array.isArray(mapinfo.mapData) &&
            mapinfo.mapData.map(marker => (
              <Marker
                key={marker._id}
                coordinate={{
                  latitude:
                    Platform.OS == "android"
                      ? isNaN(parseFloat(marker.Latitude))
                        ? 0
                        : parseFloat(marker.Latitude)
                      : marker.Latitude,
                  longitude:
                    Platform.OS == "android"
                      ? isNaN(parseFloat(marker.Longitude))
                        ? 0
                        : parseFloat(marker.Longitude)
                      : marker.Longitude
                }}
                onPress={e => {
                  setMarkerClickData(marker);
                  setMarkerClick(false);
                }}
              >
                {console.log("forceUpdate object", marker)}
                <AnimatedPriceMarker
                  onClick={forceUpdate}
                  amount={121}
                  color="#00AFF0"
                />
              </Marker>
            ))} */}
        </ClusterMap>`

**Comment by dimagreat** [comment]
It's not clear for me, because of a lot of comment lines. But I can suppose that you got your problem due to data mutation inside of your `mapinfo.mapData` array. I suggest extracting ClusterMap and API calling to different components. In one component you just fetch your markers info and sending it with props to another one with ClusterMap component
