### ISSUE TITLE
Clustering not working properly unable to expand to get makers with dynamic data.

### ISSUE THREAD

**Issue by ektasahu027** [codempireio/react-native-maps-clusterize#16]
I am passing dynamic markers at the change of viewports of maps...but clustering not working properly.

When I am clicking on cluster than it's unable to expand only shows cluster count.
Here is the code:

Parent component :

`<MapOnly
          placeName={placeName}
          setCoordinateApi={object => setCoordinateApi(object)}
          polygonDrawEnable={polygonDrawEnable}
          MapViewSet={MapViewSet}
          setMarkerClickData={object => setMarkerClickData(object)}
          setMarkerClick={data => setMarkerClick(data)}
          onPressMap={e => this.onPress(e)}
          editing={editing}
          mapinfo={mapinfo}
          apiCall1={object => this.apiCall1(object)}
        />`

Child component:

`import React, { useState } from "react";
import { View, Text } from "react-native";
import { ClusterMap } from "react-native-cluster-map";
import { Marker, ProviderPropType, Polygon } from "react-native-maps";
import AnimatedPriceMarker from "./AnimatedPriceMarker";
import styles from "./styles";`

`const useForceUpdate = () => useState()[1];
const Maps = props => {
  var map = React.createRef(null);
  renderCluster = count => {
    return (
      <View
        style={{
          width: 30,
          height: 30,
          padding: 6,
          borderWidth: 1,
          borderRadius: 15,
          alignItems: "center",
          borderColor: "#f716d2",
          justifyContent: "center",
          backgroundColor: "white"
        }}
      >
        <Text style={{ color: "#f716d2" }}>{count}</Text>
      </View>
    );
  };
  renderMarker = data => (
    <Marker key={data.id || Math.random()} coordinate={data.location} />
  );
  const mapOptions = {
    scrollEnabled: true
  };
  if (props.editing) {
    mapOptions.scrollEnabled = false;
    mapOptions.onPanDrag = e => this.onPress(e);
  }
  const forceUpdate = useForceUpdate();`

` return (
    <ClusterMap
      ref={ref => {
        MapData = ref;
      }}
      style={styles.map}
      key={`${props.placeName.latitude}`}
      scrollEnabled={props.polygonDrawEnable}
      region={{
        latitude: parseFloat(props.placeName.latitude),
        longitude: parseFloat(props.placeName.longitude),
        latitudeDelta: 1.05,
        longitudeDelta: 1.05
      }}
      mapType={props.MapViewSet}
      onPress={e => {
        if (e.nativeEvent.action !== "marker-press") {
          props.setMarkerClickData({});
          props.setMarkerClick(true);
        }
      }}
      onPanDrag={e => props.onPressMap(e)}
      renderClusterMarker={this.renderCluster}
      onRegionChangeComplete={async center => {
        if (props.polygonDrawEnable) {
          props.setCoordinateApi({
            NorthEast: [
              center.longitude + center.longitudeDelta / 2,
              center.latitude + center.latitudeDelta / 2
            ],
            SouthWest: [
              center.longitude - center.longitudeDelta / 2,
              center.latitude - center.latitudeDelta / 2
            ]
          });
          props.apiCall1({
            Coordinates: {
              NorthEast: [
                center.longitude + center.longitudeDelta / 2,
                center.latitude + center.latitudeDelta / 2
              ],
              SouthWest: [
                center.longitude - center.longitudeDelta / 2,
                center.latitude - center.latitudeDelta / 2
              ]
            }
          });
        }
      }}
      priorityMarker={
        props.editing &&
        (props.editing.coordinates.length != 0 && (
          <Polygon
            ref={map}
            key={props.editing.id}
            coordinates={props.editing.coordinates}
            holes={props.editing.holes}
            strokeColor="red"
            fillColor="rgba(0,128,0,0.3)"
            strokeWidth={4}
          />
        ))
      }
    >
      {Array.isArray(props.mapinfo) &&
        props.mapinfo.map(marker => (
          <Marker
            key={marker._id}
            coordinate={{
              latitude: marker.Coordinates[1],
              longitude: marker.Coordinates[0]
            }}
            onPress={e => {
              props.setMarkerClickData(marker);
              props.setMarkerClick(false);
            }}
          >
            <AnimatedPriceMarker
              onClick={forceUpdate}
              amount={
                Math.abs(marker.ListPrice) > 999
                  ? Math.sign(marker.ListPrice) *
                      (Math.abs(marker.ListPrice) / 1000).toFixed(1) +
                    "k"
                  : Math.sign(marker.ListPrice) * Math.abs(marker.ListPrice)
              }
              color="#00AFF0"
            />
          </Marker>
        ))}
    </ClusterMap>
  );`

`};
Maps.propTypes = {
  provider: ProviderPropType
};
export default Maps;`

**Comment by dimagreat** [comment]
Hi. Did you try to provide onClusterClick method to `ClutserMap`?

**Comment by ektasahu027** [comment]
what I do inside the onClusterClick method..... Actually, See I am calling API when map viewport got changed using onRegionChangeComplete method but there is two why to change viewport first one is changing the viewport manually and the second one is clicking on a cluster so the problem is I get new markers by clicking on cluster also because viewports also get changed at the same time that's why the cluster marker shows unless the new markers... could you please check this flow.

And **one more thing do you know how to stop cluster click functionality means I don't want to spread it just wanted to zoom out the map and fit the fresh coming markers and remove all old the cluster and markers...

could you please help me**

**Comment by dimagreat** [comment]
@ektasahu027 Almost got you. Will try to reproduce on my environment and create this feature for you!

**Comment by ektasahu027** [comment]
@dimagreat Thanks, Right now I handle it...... just stop calling API of new markers at the time of cluster clicking only spread it by cluster id.
