### ISSUE TITLE
Slow performance on zoom out.

### ISSUE THREAD

**Issue by tj1122** [codempireio/react-native-maps-clusterize#18]
Is anyone else experience slow performance when you zoom out and start to have many clusters? I do have 100+ markers but when I don't cluster them there seems to be no issue. Does nodeSize have anything to do with this?

**Comment by dimagreat** [comment]
@tj1122 thanks for an issue. In my common case when I worked with map. I'm always trying to move all complex logic to the server. And I just fetching visible region data only.
React Native has a lot of problems with performance, so it won't help you to store all data on the UI.

As suggestion you can fetch data from the server by visible region

**Comment by dimagreat** [comment]
Close because of inactivity
