### ISSUE TITLE
Proposal for onClusterClick

### ISSUE THREAD

**Issue by sprotymo** [codempireio/react-native-maps-clusterize#19]
Please, can you add coordinates in onClusterClick?

**Comment by sprotymo** [comment]
`JavaScript

this.onClusterMarkerPress = (clusterId, coordinates) => {
            const { isClusterExpandClick, onClusterClick } = this.props;
            if (isClusterExpandClick) {
                const region = clusterService.expandCluster(clusterId);
                this.mapRef.animateToRegion(region, CLUSTER_EXPAND_TIME);
            }
            onClusterClick && onClusterClick(coordinates);
        };

...
onClusterMarkerPress: () => this.onClusterMarkerPress(marker.properties.cluster_id, geometry.coordinates)
...

`

**Comment by dimagreat** [comment]
Good point, will add. You can open PR as well!

**Comment by ManigandanRaamanathan** [comment]
@dimagreat @sprotymo can we get list of items in it using clusterId? How do know the items inside the cluster?
