### ISSUE TITLE
Can someone show me how to use priorityMarker

### ISSUE THREAD

**Issue by rohithegde-sankey** [codempireio/react-native-maps-clusterize#22]
I tried using it by returning a marker with coordinates but it doesn't affect in the map

**Comment by dimagreat** [comment]
Hi @RohitHegde44 

You can setup it next way

```
      <ClusterMap
        provider={PROVIDER_GOOGLE}
        region={region}
       priorityMarker={<Marker coordinate={priorityMarkerProps} />}
      >
        {markers.map((marker, id) => {
          return <Marker coordinate={marker} key={id} />;
        })}
      </ClusterMap>

```

**Comment by RohitHegde44** [comment]
priorityMarker={
						<Marker title='Your Location' coordinate={{latitude:this.state.latitude,longitude:this.state.longitude}}>
							<Image resizeMode='center' style={{width:40,height:40}} source={require('../../../assets/images/trips/currentlocation.png')} />
						</Marker>					
					}

**Comment by RohitHegde44** [comment]
> priorityMarker={
> 
> <Image resizeMode='center' style={{width:40,height:40}} source={require('../../../assets/images/trips/currentlocation.png')} />
> 
> }

Didn't work on my map
What'd i do worng?

**Comment by RohitHegde44** [comment]
<Marker title='Your Location' coordinate={{latitude:this.state.latitude,longitude:this.state.longitude}} >
<Image resizeMode='center' style={{width:40,height:40}} source={require('../../../assets/images/trips/currentlocation.png')} />
</Marker>

**Comment by rohithegde-sankey** [comment]
Doesn't work on my map


<Marker title='Your Location' coordinate={{latitude:this.state.latitude,longitude:this.state.longitude}} >
							<Image resizeMode='center' style={{width:40,height:40}} source={require('../../../assets/images/trips/currentlocation.png')} />
						</Marker>

**Comment by dimagreat** [comment]
Share your code, I'll try to help you

**Comment by dimagreat** [comment]
Close because of inactivity
