### ISSUE TITLE
Can't fetch Directions within <ClusterMap> component.

### ISSUE THREAD

**Issue by smartsuhani** [codempireio/react-native-maps-clusterize#23]
Currently, rendering `<MapViewDirections>` component within `<ClusterMap>` component is not supported. What's the way to show directions on map now?

**Comment by dimagreat** [comment]
Hi, thanks for this issue. Will add this functionality soon

**Comment by denerator** [comment]
@smartsuhani You can pass it to the priorityMarker prop.
```
priorityMarker={
  <MapViewDirections
  origin={origin}
  destination={destination}
  apikey=''
  />
}
```

Works perfect for me.
