### ISSUE TITLE
Cluster markers lagging

### ISSUE THREAD

**Issue by Baterka** [codempireio/react-native-maps-clusterize#27]
ClusterMarker (concretely <Marker> component inside ClusterMarker) causing huge lags when moving around map, because <Marker> keeps updating.

I fixed this by defining `tracksViewChanges: false` prop to <Marker> component inside CLusterMarker.
Now, markers are not updated every render, what improves performance to usable state.

To enable dynamic updates of marker's state, something like this: https://github.com/react-native-community/react-native-maps/issues/2658#issuecomment-455731624 can be implemented.

**Comment by dimagreat** [comment]
Fixed with #30
