### ISSUE TITLE
Breaks with use of non-marker chidlren

### ISSUE THREAD

**Issue by idjokic-spiria** [codempireio/react-native-maps-clusterize#33]
The component uses all children to create clusters, not just markers. This becomes an issue when using overlays, such as Polygons, Circles, etc.

The cluster map requires the coordinate prop to be present on all children, but this prop doesn't necessarily make sense for Polygons and Polylines.

**Comment by judastheo** [comment]
Hello, I am also facing this issue, trying to render clustered marker on one side and polygons on the other side inside the same map.

**Comment by idjokic-spiria** [comment]
I made a fork here that addresses the issue. I need to clean it up a bit and make a PR but I don't know if it'll get accepted.

https://github.com/idjokic-spiria/react-native-cluster-map
