### ISSUE TITLE
ClusterMap doesn't update when region is set

### ISSUE THREAD

**Issue by kami-** [codempireio/react-native-maps-clusterize#34]
I'm trying to update the region of a `<ClusterMap/>`, however it doesn't work.
This how I'm using it:
`<ClusterMap region={this.state.region}/>` then calling `this.setState({region: {...})`

I've looked at the code and the issue seems to be with using `initialRegion` at https://github.com/codempireio/react-native-cluster-map/blob/master/src/cluster-map.tsx#L41

According to the [MapView](https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md) documentation, changing this prop will not result in the map updating and `region` should be used instead.

**Comment by idjokic-spiria** [comment]
Aye, I've run into this as well in another project. There are methods of the MapView that you can access using the nested ref, which will allow you to change the set region. This is how I implemented region change.
