### ISSUE TITLE
Is it possible to move the center location button in android? 

### ISSUE THREAD

**Issue by disrae** [codempireio/react-native-maps-clusterize#42]
As above, wondering if I can move the target icon.

![image](https://user-images.githubusercontent.com/26100016/88745286-7e73a480-d0fe-11ea-9aed-72d08cf76352.png)

**Comment by dimagreat** [comment]
Hi, @disrae Sorry, can't help you with this. Looks like this question is mostly for our dependency [react-native-maps](https://github.com/react-native-community/react-native-maps) library. I think you to look there to styling docs
