### ISSUE TITLE
cannot use native events

### ISSUE THREAD

**Issue by creeptosis** [codempireio/react-native-maps-clusterize#9]
Hi I'm just wondering if you could help me with referencing the ClusterMap & accessing MapViews base functions

<ClusterMap
            ref={(ref) => { this.mapRef = ref }}
            ...otherProps
>
</CusterMap>

// fitToCoordinates undefined..
this.mapRef.fitToCoordinates(coordinatesOnly, {
      edgePadding: DEFAULT_PADDING,
      animated: false,
    })

**Comment by dimagreat** [comment]
@creeptosis 
Hi, you can try to do this next way:

```javascript
render () {
  return <ClusterMap ref={(ref) => { this.yourRef = ref }} {...otherProps} />
}


fit () {
   this.yourRef.mapRef.fitToCoordinates()
}

```

**Comment by creeptosis** [comment]
it works thanks @dimagreat
